apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: susk8s-rescheduler-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["sustainability.susk8s"]
  resources: ["workloadpolicies"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: susk8s-rescheduler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: susk8s-rescheduler-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default