apiVersion: sustainability.susk8s/v1alpha1
kind: WorkloadPolicy
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: workloadpolicy-sample
spec:
  # TODO(user): Add fields here
